// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD9tCmjo8xG2k9lz-M0mRp9D-tWA80xoo',
    appId: '1:51432788311:web:dbca39b9d5c37672ceee12',
    messagingSenderId: '51432788311',
    projectId: 'losmaitenes-24104',
    authDomain: 'losmaitenes-24104.firebaseapp.com',
    storageBucket: 'losmaitenes-24104.firebasestorage.app',
    measurementId: 'G-ZD9ZK1P09Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa85tdwoGRGtp5qYkvHgRIfNVbV6GvoaY',
    appId: '1:51432788311:android:1a92a78039cd1030ceee12',
    messagingSenderId: '51432788311',
    projectId: 'losmaitenes-24104',
    storageBucket: 'losmaitenes-24104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDZMc5JatGOcIt-Vb7q2HmDyiEsxCzcKY',
    appId: '1:51432788311:ios:4c98d716ae97c2eaceee12',
    messagingSenderId: '51432788311',
    projectId: 'losmaitenes-24104',
    storageBucket: 'losmaitenes-24104.firebasestorage.app',
    iosBundleId: 'com.example.losMaitenes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDZMc5JatGOcIt-Vb7q2HmDyiEsxCzcKY',
    appId: '1:51432788311:ios:4c98d716ae97c2eaceee12',
    messagingSenderId: '51432788311',
    projectId: 'losmaitenes-24104',
    storageBucket: 'losmaitenes-24104.firebasestorage.app',
    iosBundleId: 'com.example.losMaitenes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD9tCmjo8xG2k9lz-M0mRp9D-tWA80xoo',
    appId: '1:51432788311:web:81dc4d3c954a2338ceee12',
    messagingSenderId: '51432788311',
    projectId: 'losmaitenes-24104',
    authDomain: 'losmaitenes-24104.firebaseapp.com',
    storageBucket: 'losmaitenes-24104.firebasestorage.app',
    measurementId: 'G-NDGXYFK5D3',
  );
}
